/*
 * AutoSnakeView.java
 */
package autosnake;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.Timer;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class AutoSnakeView extends FrameView implements ASCommon, KeyListener {

    public AutoSnakeView(SingleFrameApplication app) {
        super(app);
        initComponents();
        JFrame mainFrame = getFrame();
        mainFrame.setSize(400, 300);
        mainFrame.setLocation(200, 200);
        mainFrame.setResizable(false);
        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();

        scanvas = new SCanvas();
        snake = new Snake(t);
        goal = new Goal();
        initCanvas();
        goal.generate(snake);
        snake.setGoal(goal);
        t.start();
    }

    public void keyPressed(KeyEvent e) {
    }

    public void keyTyped(KeyEvent e) {
        /*switch (e.getKeyCode()) {
        case KeyEvent.VK_LEFT:
        move = GameMove.LEFT;
        break;
        case KeyEvent.VK_RIGHT:
        move = GameMove.RIGHT;
        break;
        case KeyEvent.VK_DOWN:
        move = GameMove.DROP;
        break;
        case KeyEvent.VK_SHIFT:
        move = GameMove.CW;
        break;
        case KeyEvent.VK_ENTER:
        move = GameMove.DROP;
        break;
        }*/
        /*if (e.getKeyCode() == KeyEvent.VK_LEFT) {
        } else if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
        } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
        } else if (e.getKeyCode() == KeyEvent.VK_SHIFT) {
        }*/
    }

    public void keyReleased(KeyEvent e) {
    }

    //@Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = AutoSnakeApp.getApplication().getMainFrame();
            aboutBox = new AutoSnakeAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        AutoSnakeApp.getApplication().show(aboutBox);
    }

    public void initCanvas() {
        scanvas.setSize(SWIDTH, SHEIGHT);
        scanvas.setBackground(Color.WHITE);
        mainPanel.add(scanvas);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 278, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(autosnake.AutoSnakeApp.class).getContext().getResourceMap(AutoSnakeView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(autosnake.AutoSnakeApp.class).getContext().getActionMap(AutoSnakeView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    private JDialog aboutBox;
    private SCanvas scanvas;
    private Snake snake;
    private Goal goal;
    private Timer t = new javax.swing.Timer(100, new ActionListener() {

        public void actionPerformed(ActionEvent e) {
            scanvas.setMap(snake.getMap());
            scanvas.repaint();
            if (snake.isAlive()) {
                snake.move();
            }
        }
    });
}
